version: '3.4'
services:
  spdbridge:
    image: ghcr.io/seprinder-org/spdbridge:master
    build:
      dockerfile: docker/Dockerfile-prod
      context: .
      # network: host
    container_name: "spdbridge"
    ports:
      - 1122:1122
    restart: always
    # networks:
    #   - spdnetwork
# networks:
#   spdnetwork:
#     name: spdnetwork
#     driver: bridge