FROM python:3.10

WORKDIR /code

COPY ./scripts/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

EXPOSE 1122

CMD ["python3", "plugin/main.py"]
